print 2 ^ 3;
try {
    print 5 /;
} catch (e) {
    print "Caught exception:";
    print e;
} finally {
    print "Finally";
}
